[package]
name = "anomalies-derive"
version = "0.2.2"
edition = "2024"
description = "Derive macros for the anomalies crate"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ahammel/anomalies"
keywords = ["error", "error-handling", "anomaly", "derive"]
categories = ["rust-patterns"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
