[package]
name = "anomalies"
version = "0.2.1"
edition = "2024"
description = "Structured, categorized error handling inspired by Cognitect's anomalies"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ahammel/anomalies"
readme = "../README.md"
keywords = ["error", "error-handling", "anomaly"]
categories = ["rust-patterns"]

[dependencies]
anomalies-derive = { path = "../anomalies-derive", version = "0.2.0" }

[dev-dependencies]
trybuild = "1"
